language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rodoljub-radivojevic/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true rodoljub-radivojevic/docker-react npm run test