language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t https://hub.docker.com/repository/docker/rodoljubradivojevic/docker_react:v2 -f Dockerfile.dev .
  - docker push https://hub.docker.com/repository/docker/rodoljubradivojevic/docker_react:v2

script:
  - docker run -e CI=true rodoljubradivojevic/docker-react npm run test