language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rodoljubradivojevic/docker_react:v3 -f Dockerfile.dev .

script:
  - docker run -e CI=true rodoljubradivojevic/docker-react:v3 npm run test