language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rodoljubradivojevic/docker_react:v2 -f Dockerfile.dev .
  - docker push rodoljubradivojevic/docker_react:v2

script:
  - docker run -e CI=true rodoljubradivojevic/docker-react:v2 npm run test